name: XYC
version: ${project.version}
description: Provides some utilities for plugins to hook into.
author: xxyy
website: http://xxyy.github.io/
load: STARTUP

main: io.github.xxyy.common.internal.CommonPlugin

